
import { WorkoutData, WorkoutDataExtended } from '@/types/workout';

/**
 * Formats raw workout data from the database into a standardized structure
 */
export const formatWorkout = (workout: WorkoutDataExtended): WorkoutData => {
  let parsedExercises: any = [];
  let isPack = false;
  let packItems: any[] = [];
  
  try {
    if (typeof workout.exercises === 'string') {
      parsedExercises = JSON.parse(workout.exercises);
    } else {
      parsedExercises = workout.exercises || [];
    }
  } catch (e) {
    console.error('Error parsing exercises:', e);
  }
  
  const isWorkoutPack = 
    typeof parsedExercises === 'object' && 
    parsedExercises !== null &&
    'isWorkoutPack' in parsedExercises && 
    parsedExercises.isWorkoutPack === true;
  
  if (isWorkoutPack) {
    isPack = true;
    
    if ('originalWorkouts' in parsedExercises && Array.isArray(parsedExercises.originalWorkouts)) {
      packItems = parsedExercises.originalWorkouts.map((workout: any) => ({
        id: workout.id || crypto.randomUUID(),
        title: workout.name || "AI Workout Exercise",
        type: "AI_EXERCISE",
        description: Array.isArray(workout.instructions) ? workout.instructions[0] : "AI-generated exercise",
        level: "custom",
        duration: workout.duration || 60,
        calories_burned: workout.calories_burned || 100,
        exercises: [workout],
        image: workout.gifUrl || "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"
      }));
    } else if ('list' in parsedExercises && Array.isArray(parsedExercises.list)) {
      packItems = parsedExercises.list.map((exercise: any) => ({
        id: crypto.randomUUID(),
        title: exercise.name || "AI Exercise",
        type: "AI_EXERCISE",
        description: Array.isArray(exercise.instructions) ? exercise.instructions[0] : "AI-generated exercise",
        level: "custom",
        duration: exercise.duration || 60,
        calories_burned: exercise.calories_burned || 100,
        exercises: [exercise],
        image: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"
      }));
    }
  }
  
  const calorieValue = workout.calories_burned || 300;
  
  return {
    ...workout,
    id: workout.id || crypto.randomUUID(),
    exercises: parsedExercises,
    calories_burned: calorieValue,
    caloriesBurn: calorieValue,
    level: workout.level || "custom",
    description: workout.description || (isPack 
      ? `AI-generated workout pack with ${packItems.length} focused exercises` 
      : "Custom workout generated by AI assistant"),
    image: workout.image || (isPack
      ? "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" 
      : "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80"),
    isPack,
    packItems,
    title: workout.title || "Untitled Workout",
    type: workout.type || "CUSTOM"
  } as WorkoutData;
};

/**
 * Collection of default workout plans
 */
export const defaultWorkoutPlans: WorkoutData[] = [
  {
    id: "1",
    title: "Full Body HIIT Challenge",
    type: "HIIT",
    description: "High intensity interval training to build strength and endurance.",
    level: "beginner",
    duration: 30,
    calories_burned: 300,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Jumping Jacks",
        sets: 3,
        reps: 20,
        duration: 60,
        restTime: 30,
        instructions: [
          "Start with your feet together and arms at your sides",
          "Jump up and spread your feet beyond shoulder-width while bringing your arms above your head",
          "Jump again to return to the starting position",
          "Repeat for the specified number of reps"
        ]
      },
      {
        name: "Push-ups",
        sets: 3,
        reps: 10,
        duration: 60,
        restTime: 30,
        instructions: [
          "Start in a plank position with your hands shoulder-width apart",
          "Lower your body until your chest nearly touches the floor",
          "Push yourself back up to the starting position",
          "Keep your body in a straight line throughout the movement"
        ]
      },
      {
        name: "Air Squats",
        sets: 3,
        reps: 15,
        duration: 60,
        restTime: 30,
        instructions: [
          "Stand with feet shoulder-width apart",
          "Push your hips back and bend your knees as if sitting in a chair",
          "Lower until your thighs are parallel to the ground",
          "Push through your heels to return to starting position"
        ]
      }
    ]
  },
  {
    id: "2",
    title: "Core Focus & Strength",
    type: "CORE",
    description: "Build a strong core with this targeted workout routine.",
    level: "intermediate",
    duration: 25,
    calories_burned: 200,
    image: "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Plank",
        sets: 3,
        reps: 1,
        duration: 45,
        restTime: 30,
        instructions: [
          "Start in a push-up position but with your weight on your forearms",
          "Keep your body in a straight line from head to heels",
          "Engage your core and hold the position",
          "Breathe normally and maintain good form"
        ]
      },
      {
        name: "Russian Twists",
        sets: 3,
        reps: 15,
        duration: 60,
        restTime: 30,
        instructions: [
          "Sit on the floor with knees bent and feet lifted slightly",
          "Lean back slightly to engage your core",
          "Twist your torso from side to side",
          "Touch the floor beside your hips with each twist"
        ]
      },
      {
        name: "Mountain Climbers",
        sets: 3,
        reps: 20,
        duration: 60,
        restTime: 30,
        instructions: [
          "Start in a plank position with arms straight",
          "Bring one knee toward your chest",
          "Return it to the starting position while bringing the other knee forward",
          "Continue alternating at a quick pace"
        ]
      }
    ]
  },
  {
    id: "3",
    title: "Energizing Yoga Flow",
    type: "YOGA",
    description: "Increase flexibility and mindfulness with this yoga routine.",
    level: "all",
    duration: 45,
    calories_burned: 150,
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Sun Salutation (Surya Namaskar)",
        sets: 3,
        reps: 1,
        duration: 120,
        restTime: 30,
        instructions: [
          "Start in mountain pose (Tadasana)",
          "Inhale, raise your arms overhead",
          "Exhale, fold forward",
          "Inhale, halfway lift",
          "Exhale, step or jump back to plank",
          "Lower to chaturanga",
          "Inhale to upward facing dog",
          "Exhale to downward facing dog",
          "Step forward and return to mountain pose"
        ]
      },
      {
        name: "Warrior II (Virabhadrasana II)",
        sets: 2,
        reps: 1,
        duration: 60,
        restTime: 20,
        instructions: [
          "Step your feet wide apart",
          "Turn your right foot out 90 degrees and left foot in slightly",
          "Extend your arms parallel to the floor",
          "Bend your right knee over your ankle",
          "Gaze over your right fingertips",
          "Hold and breathe deeply",
          "Repeat on the other side"
        ]
      },
      {
        name: "Tree Pose (Vrksasana)",
        sets: 2,
        reps: 1,
        duration: 60,
        restTime: 20,
        instructions: [
          "Start standing with feet together",
          "Shift your weight to one foot",
          "Place the sole of your other foot on your inner thigh",
          "Bring your hands to prayer position or extend overhead",
          "Focus your gaze on a fixed point",
          "Hold and breathe deeply",
          "Repeat on the other side"
        ]
      }
    ]
  },
  // Additional workouts
  {
    id: "4",
    title: "Full Body HIIT",
    type: "HIIT",
    description: "High intensity interval training to burn calories and improve cardiovascular health.",
    level: "intermediate",
    duration: 30,
    calories_burned: 320,
    image: "https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Jumping Jacks",
        sets: 3,
        reps: 20,
        duration: 60,
        restTime: 30,
        instructions: [
          "Stand upright with your legs together and arms at your sides",
          "Jump up and spread your feet beyond shoulder width while bringing arms above head",
          "Return to starting position and repeat"
        ]
      },
      {
        name: "Push-ups",
        sets: 3,
        reps: 10,
        duration: 60,
        restTime: 30,
        instructions: [
          "Start in a plank position with hands shoulder-width apart",
          "Lower your body until chest nearly touches the floor",
          "Push back up and repeat"
        ]
      },
      {
        name: "Mountain Climbers",
        sets: 3,
        reps: 20,
        duration: 60,
        restTime: 30,
        instructions: [
          "Start in a plank position",
          "Drive one knee toward your chest, then quickly switch legs",
          "Continue alternating legs at a rapid pace"
        ]
      },
      {
        name: "Bodyweight Squats",
        sets: 3,
        reps: 15,
        duration: 60,
        restTime: 30,
        instructions: [
          "Stand with feet shoulder-width apart",
          "Lower your body by bending knees and pushing hips back",
          "Return to standing position and repeat"
        ]
      }
    ]
  },
  {
    id: "5",
    title: "Core Crusher",
    type: "Strength Training",
    description: "Focus on your core with this targeted ab workout.",
    level: "beginner",
    duration: 20,
    calories_burned: 180,
    image: "https://images.unsplash.com/photo-1567598508481-65a7a5553141?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Plank",
        sets: 3,
        reps: 1,
        duration: 30,
        restTime: 20,
        instructions: [
          "Start in a forearm plank position, elbows under shoulders",
          "Engage your core and keep your body in a straight line",
          "Hold the position for the duration"
        ]
      },
      {
        name: "Crunches",
        sets: 3,
        reps: 15,
        duration: 45,
        restTime: 30,
        instructions: [
          "Lie on your back with knees bent",
          "Place hands behind your head or across chest",
          "Lift shoulders off the ground and engage core",
          "Lower back down with control and repeat"
        ]
      },
      {
        name: "Russian Twists",
        sets: 3,
        reps: 20,
        duration: 45,
        restTime: 30,
        instructions: [
          "Sit on the floor with knees bent",
          "Lean back slightly, keeping back straight",
          "Twist torso to right, then to left (counts as one rep)",
          "Keep feet slightly off the ground for added challenge"
        ]
      }
    ]
  },
  {
    id: "6",
    title: "Upper Body Blast",
    type: "Strength Training",
    description: "Build strength in your chest, shoulders, and arms.",
    level: "intermediate",
    duration: 35,
    calories_burned: 250,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Push-ups",
        sets: 4,
        reps: 12,
        duration: 60,
        restTime: 45,
        instructions: [
          "Start in a plank position with hands shoulder-width apart",
          "Lower your body until chest nearly touches the floor",
          "Push back up and repeat"
        ]
      },
      {
        name: "Dips",
        sets: 3,
        reps: 10,
        duration: 60,
        restTime: 45,
        instructions: [
          "Use a chair or bench behind you",
          "Place hands on edge with fingers facing forward",
          "Lower your body by bending elbows",
          "Push back up and repeat"
        ]
      },
      {
        name: "Arm Circles",
        sets: 3,
        reps: 20,
        duration: 45,
        restTime: 30,
        instructions: [
          "Stand with feet shoulder-width apart",
          "Extend arms out to sides at shoulder height",
          "Make small circles forward, then backward"
        ]
      },
      {
        name: "Plank to Push-up",
        sets: 3,
        reps: 8,
        duration: 60,
        restTime: 45,
        instructions: [
          "Start in a forearm plank position",
          "Push up to a hand plank, one arm at a time",
          "Lower back to forearm plank, one arm at a time",
          "Repeat, alternating which arm moves first"
        ]
      }
    ]
  },
  {
    id: "7",
    title: "Yoga Flow",
    type: "Yoga",
    description: "A gentle flow to improve flexibility, balance, and mindfulness.",
    level: "all",
    duration: 45,
    calories_burned: 200,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Sun Salutation",
        sets: 3,
        reps: 1,
        duration: 120,
        restTime: 30,
        instructions: [
          "Start in mountain pose (Tadasana)",
          "Raise arms overhead on inhale",
          "Forward fold on exhale",
          "Step or jump back to plank pose",
          "Lower to chaturanga dandasana",
          "Upward facing dog, downward facing dog",
          "Step forward and return to mountain pose"
        ]
      },
      {
        name: "Warrior Sequence",
        sets: 2,
        reps: 1,
        duration: 180,
        restTime: 45,
        instructions: [
          "From downward dog, step right foot forward",
          "Rise up into Warrior I pose",
          "Open hips and arms to Warrior II",
          "Reverse Warrior with back arm down, front arm up",
          "Return to center and repeat on other side"
        ]
      },
      {
        name: "Balance Series",
        sets: 2,
        reps: 1,
        duration: 120,
        restTime: 30,
        instructions: [
          "Start with Tree Pose on right leg",
          "Transition to Eagle Pose if comfortable",
          "Return to center and repeat on left side",
          "Move slowly and use a wall for support if needed"
        ]
      }
    ]
  },
  {
    id: "8",
    title: "Cardio Kickstart",
    type: "Cardio",
    description: "Heart-pumping cardio workout to boost endurance and burn calories.",
    level: "beginner",
    duration: 25,
    calories_burned: 280,
    image: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Jumping Jacks",
        sets: 3,
        reps: 30,
        duration: 60,
        restTime: 20,
        instructions: [
          "Start with feet together and arms at sides",
          "Jump to spread legs and bring arms overhead",
          "Jump back to starting position",
          "Maintain a steady rhythm"
        ]
      },
      {
        name: "High Knees",
        sets: 3,
        reps: 40,
        duration: 45,
        restTime: 25,
        instructions: [
          "Stand with feet hip-width apart",
          "Run in place, bringing knees up toward chest",
          "Pump arms in opposition to legs",
          "Keep core engaged throughout"
        ]
      },
      {
        name: "Burpees",
        sets: 3,
        reps: 10,
        duration: 60,
        restTime: 30,
        instructions: [
          "Begin in standing position",
          "Drop down into squat position, placing hands on floor",
          "Kick feet back into plank position",
          "Perform a push-up (optional)",
          "Return feet to squat position",
          "Jump up explosively with hands overhead"
        ]
      },
      {
        name: "Lateral Jumps",
        sets: 3,
        reps: 20,
        duration: 45,
        restTime: 25,
        instructions: [
          "Stand with feet together",
          "Jump sideways 1-2 feet to the right",
          "Jump back to the left",
          "Keep knees soft to absorb impact"
        ]
      }
    ]
  },
  {
    id: "9",
    title: "Lower Body Focus",
    type: "Strength Training",
    description: "Build strong, toned legs and glutes with this targeted workout.",
    level: "intermediate",
    duration: 40,
    calories_burned: 300,
    image: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Bodyweight Squats",
        sets: 4,
        reps: 15,
        duration: 60,
        restTime: 40,
        instructions: [
          "Stand with feet shoulder-width apart",
          "Lower your hips back and down as if sitting in a chair",
          "Keep chest up and knees aligned with toes",
          "Push through heels to return to standing"
        ]
      },
      {
        name: "Lunges",
        sets: 3,
        reps: 12,
        duration: 60,
        restTime: 40,
        instructions: [
          "Stand with feet together",
          "Step forward with right foot into a lunge",
          "Lower until both knees form 90-degree angles",
          "Push through front heel to return to start",
          "Alternate legs with each rep"
        ]
      },
      {
        name: "Glute Bridges",
        sets: 3,
        reps: 15,
        duration: 45,
        restTime: 30,
        instructions: [
          "Lie on your back with knees bent, feet flat on floor",
          "Pushing through heels, lift hips toward ceiling",
          "Squeeze glutes at the top",
          "Lower with control and repeat"
        ]
      },
      {
        name: "Calf Raises",
        sets: 3,
        reps: 20,
        duration: 45,
        restTime: 30,
        instructions: [
          "Stand with feet hip-width apart",
          "Rise up onto balls of feet, lifting heels high",
          "Pause briefly at the top",
          "Lower with control and repeat",
          "Hold onto a wall for balance if needed"
        ]
      }
    ]
  },
  {
    id: "10",
    title: "Beginner Full Body",
    type: "Strength Training",
    description: "Perfect starter workout to build strength across all major muscle groups.",
    level: "beginner",
    duration: 25,
    calories_burned: 200,
    image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Bodyweight Squats",
        sets: 3,
        reps: 12,
        duration: 45,
        restTime: 30,
        instructions: [
          "Stand with feet shoulder-width apart",
          "Lower your body as if sitting in a chair",
          "Keep chest up and knees behind toes",
          "Return to standing position"
        ]
      },
      {
        name: "Modified Push-ups",
        sets: 3,
        reps: 8,
        duration: 45,
        restTime: 30,
        instructions: [
          "Start with knees on the floor and hands shoulder-width apart",
          "Keep your back straight and core engaged",
          "Lower your chest toward the floor",
          "Push back up to starting position"
        ]
      },
      {
        name: "Glute Bridges",
        sets: 3,
        reps: 12,
        duration: 45,
        restTime: 30,
        instructions: [
          "Lie on your back with knees bent and feet flat on the floor",
          "Push through your heels to lift your hips toward the ceiling",
          "Squeeze your glutes at the top",
          "Lower back down with control"
        ]
      },
      {
        name: "Standing Dumbbell Curls",
        sets: 3,
        reps: 10,
        duration: 45,
        restTime: 30,
        instructions: [
          "Stand with feet hip-width apart holding light dumbbells",
          "Keep elbows close to your sides",
          "Curl weights up toward shoulders",
          "Lower with control and repeat"
        ]
      }
    ]
  },
  {
    id: "11",
    title: "5K Running Program",
    type: "Cardio",
    description: "Progressive running workout to build endurance for a 5K race.",
    level: "intermediate",
    duration: 30,
    calories_burned: 300,
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Warm-up Walk",
        sets: 1,
        reps: 1,
        duration: 300,
        restTime: 0,
        instructions: [
          "Start with a brisk 5-minute walk to warm up",
          "Focus on proper posture and breathing",
          "Gradually increase your pace to prepare for running"
        ]
      },
      {
        name: "Run/Walk Intervals",
        sets: 6,
        reps: 1,
        duration: 240,
        restTime: 60,
        instructions: [
          "Run at a comfortable pace for 3 minutes",
          "Walk for 1 minute to recover",
          "Repeat the pattern 6 times",
          "Focus on maintaining good form throughout"
        ]
      },
      {
        name: "Cool Down Walk",
        sets: 1,
        reps: 1,
        duration: 300,
        restTime: 0,
        instructions: [
          "Slow to a comfortable walking pace",
          "Continue for 5 minutes to gradually lower heart rate",
          "Focus on deep breathing to help recovery"
        ]
      }
    ]
  },
  {
    id: "12",
    title: "Morning Stretch Routine",
    type: "Flexibility",
    description: "Gentle morning stretches to improve flexibility and start your day energized.",
    level: "all",
    duration: 15,
    calories_burned: 80,
    image: "https://images.unsplash.com/photo-1552196563-55cd4e45efb3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    exercises: [
      {
        name: "Cat-Cow Stretch",
        sets: 1,
        reps: 10,
        duration: 60,
        restTime: 0,
        instructions: [
          "Start on all fours with hands under shoulders and knees under hips",
          "Inhale and arch your back, lifting your head (cow)",
          "Exhale and round your spine, tucking your chin (cat)",
          "Flow between positions with your breath"
        ]
      },
      {
        name: "Standing Side Bends",
        sets: 1,
        reps: 8,
        duration: 60,
        restTime: 0,
        instructions: [
          "Stand with feet hip-width apart",
          "Reach one arm overhead and lean to the opposite side",
          "Hold for 15 seconds, then switch sides",
          "Breathe deeply throughout the stretch"
        ]
      },
      {
        name: "World's Greatest Stretch",
        sets: 1,
        reps: 6,
        duration: 90,
        restTime: 0,
        instructions: [
          "Start in a push-up position",
          "Step right foot outside right hand",
          "Rotate torso and extend right arm toward ceiling",
          "Return to start and repeat on left side"
        ]
      },
      {
        name: "Lying Spinal Twist",
        sets: 1,
        reps: 1,
        duration: 60,
        restTime: 0,
        instructions: [
          "Lie on your back with arms extended to sides",
          "Bend knees and lower them to one side while keeping shoulders flat",
          "Hold for 30 seconds",
          "Repeat on other side"
        ]
      }
    ]
  }
];

